import Head from "next/head";
import { useRouter } from "next/router";
import TaskCard from "../../components/taskCard";
import { useGetTask } from "../../hooks/useGetTask";
import Header from "../../layout/header";
import NavigationBar from "../../layout/navigationBar";

export default function TaskPage() {
  const router = useRouter();
  const { task_id } = router.query;

  ////// temporary hack to see how it looks with data
  const { isLoading, task } = useGetTask(task_id as string);
  //////

  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between h-full">
        <Header />
        {task ? <TaskCard type="extended" task={task} /> : <p>no data</p>}
        <NavigationBar />
      </div>
    </div>
  );
}
