import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../layout/header";
import NavigationBar from "../layout/navigationBar";
import TaskCard from "../components/taskCard";
import { useEffect, useState } from "react";

export interface Task {
	title: string;
	points: number;
	endTime: string;
	endDate: string;
	note: string;
	id: number;
	status: boolean;
}

const Home: NextPage = () => {
	const [isLoading, setIsLoading] = useState(false);

	const [tasks, setTasks] = useState<Task[]>([]);
	useEffect(() => {
		if (!isLoading) {
			fetch("http://localhost:3004/tasks")
				.then((res) => res.json())
				.then((res) => setTasks(res));
		}
	}, [isLoading]);
	return (
		<div className="h-screen">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col justify-between h-full">
				<Header />
				<div className="flex justify-center">
					<div className="flex flex-col gap-3">
						{tasks.slice(0, 3).map((task) => (
							<TaskCard
								task={task}
								key={task.id}
								isLoading={isLoading}
								setIsLoading={setIsLoading}
							></TaskCard>
						))}
					</div>
				</div>
				<NavigationBar />
			</div>
		</div>
	);
};

export default Home;
