import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../layout/header";
import NavigationBar from "../layout/navigationBar";
import TaskCard from "../components/taskCard";
import { useGetTasks } from "../hooks/useGetTasks";
import ExpandedTaskCard from "../components/expandedTaskCard";
import Link from "next/link";

export default function Home() {
  const { setIsLoading, isLoading, tasks, setTasks } = useGetTasks();

  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between h-full">
        <Header />
        <div className="flex flex-col w-full px-4 justify-center gap-4">
          {!isLoading &&
            tasks.map((task) => (
              <Link href={`/task/${task.id}`}>
                <a>
                  <TaskCard
                    type="preview"
                    task={task}
                    key={task.id}
                    isLoading={isLoading}
                    setIsLoading={setIsLoading}
                  ></TaskCard>
                </a>
              </Link>
            ))}
        </div>
        <NavigationBar />
      </div>
    </div>
  );
}
