import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../layout/header";
import NavigationBar from "../layout/navigationBar";
import TaskCard from "../components/taskCard";
import { useGetTasks } from "../hooks/useGetTasks";

const Home: NextPage = () => {
	const { setIsLoading, isLoading, tasks, setTasks } = useGetTasks();

	return (
		<div className="h-screen">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col justify-between h-full">
				<Header />
				<div className="flex flex-col w-full px-4 justify-center gap-4">
					{!isLoading &&
						tasks.map((task) => (
							<TaskCard
								type="preview"
								task={task}
								key={task.id}
								isLoading={isLoading}
								setIsLoading={setIsLoading}
							></TaskCard>
						))}
				</div>
				<NavigationBar />
			</div>
		</div>
	);
};

export default Home;
